### ISSUE TITLE
run docker error  Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/sensors'.

### ISSUE THREAD

**Issue by sky-sunny** [gunt3001/umipro-fancontroller#3]
root@ubuntu:~/umipro-fancontroller# docker run -it umipro3:fan 
Interval set as 5 seconds
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/sensors'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at umipro_fancontroller.Program.Main(String[] args) in /app/Program.cs:line 34

**Comment by gunt3001** [comment]
Hey I sort of missed this. 

FYI this code is for my own use. It does control fans, but it's specific to the fans on my machine and most likely won't work anywhere else.
